### ISSUE TITLE
The English caption of Episode 19 Door 3 is not correct

### ISSUE THREAD

**Issue by yutaro-ito** [muggy83/The-MBSE-Podcast#30]
@muggy83
Probably you uploaded the incorrect English caption for Episode 19 Door 3.
https://www.youtube.com/watch?v=ia4E5j7l3tE

It looks that the caption of Door 4 was uploaded for Door 3.
Could you please check it and upload the correct SRT file?

**Comment by muggy83** [comment]
I´m not sure, how this could happen.
I uploaded your new english version.

Can we close the issue?

**Comment by yutaro-ito** [comment]
Hmm, it looks that the issue has not been solved yet... :thinking: 

![Door3_with_caption](https://user-images.githubusercontent.com/76211629/155471578-540cd7c3-62f0-4491-9b91-bd83291ef819.png)

**Comment by muggy83** [comment]
But now it should be done :-D

**Comment by muggy83** [comment]
But now it should be done :-D

**Comment by yutaro-ito** [comment]
@muggy83 
It looks that the issue was solved.
Thank you!
